MASTERDIR="/usr/local/etc/namedb/master"
keygen="/usr/local/bin/dnssec-keygen"
signzone="/usr/local/bin/dnssec-signzone"
dsfromkey="/usr/local/bin/dnssec-dsfromkey"
KSK_PARAM="-n zone -a ED25519 -f ksk"
KSK_ONLY="YES"
SIGN_PARAM="-N unixtime -x -z"
RELOADALL_COMMAND="/usr/local/sbin/rndc -k /usr/local/etc/namedb/rndc.key -s 127.0.0.1 reload"
