keygen="/usr/local/bin/ldns-keygen"
signzone="/usr/local/bin/ldns-signzone"
dsfromkey="/usr/local/bin/ldns-key2ds -n"
MASTERDIR="/etc/nsd"
KSK_PARAM="-a ECDSAP256SHA256"
KSK_ONLY="YES"
INCEPTION=`perl -e 'print int((time - 3600)/3600)*3600;'`
EXPIRATION=`perl -e "print $INCEPTION + 86400 * 30 + 3600;"`
SIGN_PARAM="-u -i $INCEPTION -e $EXPIRATION"
RELOADALL_COMMAND="/usr/local/sbin/nsd-control reload" 
